[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "gee_s1_processing"
version = "0.1.0"
description = "S1 processing package."
readme = "README.md"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python"
]
requires-python = ">=3.10"
license = { "file" = "LICENSE" }

dependencies = [
    "earthengine-api>=1.6.6",
]

[tool.flit.module]
name = "gee_s1_processing"

[tool.flit.sdist]
include = ["gee_s1_processing/**"]

[project.urls]
source = "https://github.com/LSCE-forest/gee_s1_processing"
tracker = "https://github.com/LSCE-forest/gee_s1_processing/issues"

[project.optional-dependencies]
dev = [
    "pytest",
    "pre-commit",
    "ruff",
    "types-retry",
    "types-requests",
    "pydoclint[flake8]",
]

[tool.ruff]
target-version = "py310"
line-length = 100
[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # pydocstyle and pydoclint
    # "D",
    "DOC",
    # flake8-use-pathlib
    "PTH",
    # flake8-logging
    "LOG",
    # flake8-no-pep420
    "INP",
    "PIE",
    "T20",
    # pytest
    "PT",
]
ignore = ["DOC501", "DOC201"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.extend-per-file-ignores]
"tests/*.py" = ["INP001"]
"docs/**/*.py" = ["INP001"]

[tool.pydoclint]
style = "numpy"
skip-checking-raises = true
check-style-mismatch = true
ignore = [
    "DOC201",
    "DOC202",
    "DOC402",
    "DOC403",
    "DOC501",
    "DOC501",
] # ignore what ruff implements

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = ["slow"]
log_cli = true
log_cli_level = "DEBUG"
log_level = "DEBUG"

[tool.pyright]
typeCheckingMode = "off"